### User Registration
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "Rockez666",
  "email": "ghertalilian2006@gmail.com",
  "password": "12345678"
}

### User Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Rockez666",
  "password": "12345678"
}

> {%
    if (response && response.body) {
        const { accessToken, refreshToken } = response.body;
        client.global.set("accessToken", accessToken);
        console.log("Access token successfully set:", accessToken);

        client.global.set("refreshToken", refreshToken);
        console.log("Refresh token successfully set:", refreshToken);

    } else {
        console.error("Response body is undefined or empty.");
    }
%}

### Request Register
POST http://localhost:8080/request/register
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "ghertalilian2006@gmail.com",
  "text": "hello, user!"
}

### Refresh Token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    console.log("Raw response:", response);
    if (response && response.body) {
        const { accessToken, refreshToken } = response.body;

        if (accessToken && refreshToken) {
            client.global.set("accessToken", accessToken);
            console.log("New access token successfully set:", accessToken);

            client.global.set("refreshToken", refreshToken);
            console.log("New refresh token successfully set:", refreshToken);
        } else {
            console.error("Tokens not found in response body.");
        }
    } else {
        console.error("Response body is undefined or empty.");
    }
%}



